eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: api-gateway
server:
  port: 9500
zuul:
  routes:
    elevalue:
      path: /elevalue/**
      serviceId: eleserver
      stripPrefix: false
    consumer:
      path: /consumer/**
      serviceId: consumer
      stripPrefix: false

    webapp:
      path: /baidu/**
      sensitive-headers: Set-Cookie
      url: http://www.baidu.com
      stripPrefix: true
