spring:
  application:
    name: api-gateway
server:
  port: 9500
zuul:
  routes:
    elevalue:
      path: /elevalue/**
      serviceId: eleserver
      stripPrefix: false
    consumer:
      path: /consumer/**
      serviceId: consumer
      stripPrefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/